// Generated by Wrangler on Tue Jul 30 2024 17:15:28 GMT+1000 (Australian Eastern Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	COMPANY_NAME: "Next.js";
	TWITTER_CREATOR: "@nextjs";
	TWITTER_SITE: "https://nextjs.org/commerce";
	SITE_NAME: "Acme Store";
	SHOPIFY_REVALIDATION_SECRET: "";
	SHOPIFY_STORE_DOMAIN: "https://graphql.myshopify.com";
	SHOPIFY_STOREFRONT_ACCESS_TOKEN: string;
}
