#:schema node_modules/wrangler/config-schema.json
name = "nextjs-commerce"
compatibility_date = "2024-05-02"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
COMPANY_NAME = "Next.js"
TWITTER_CREATOR = "@nextjs"
TWITTER_SITE = "https://nextjs.org/commerce"
SITE_NAME = "Acme Store"
SHOPIFY_REVALIDATION_SECRET = ""
SHOPIFY_STORE_DOMAIN = "https://graphql.myshopify.com"
