#:schema node_modules/wrangler/config-schema.json
name = "hello-app"
main = ".next/standalone/worker.mjs"
assets = ".next/assets"
compatibility_date = "2024-07-01"
compatibility_flags = ["experimental:nodejs_compat_v2"]
workers_dev = true
minify = true

[alias]
"critters" = "./scripts/shim-throw.mjs"
"@opentelemetry/api" = "./scripts/shim-throw.mjs"
